version: '2.1'

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: The is the untagged job
          command: echo "You'll see me, regardless of tags"
          
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: The is the tagged job
          command: echo "You'll see me if there's a tag starting with v"
  
workflows:
  build-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
